name: Build Package and Push

on:
  push:
    branches:
      - master
  # release:
  #   types: [published]

jobs:
  build_push:
    runs-on: ubuntu-latest 
    steps:
      - id: leverage
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: binbashar
          repo: leverage
          excludes: prerelease, draft

      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2

      - name: install_dependencies
        run: |
          pip install GitPython
          pip install yaenv
        shell: bash

      - name: bump_version
        run: |
          echo $RELEASE_VERSION
        shell: bash
        env:
          RELEASE_VERSION: ${{ steps.leverage.outputs.release }}

      # - name: build
      #   run: |
      #     TODO
      
      # - name: upload
      #   run: 
      #     TODO
