name: Build Package and Push

on:
  push:
    branches:
      - master
  # release:
  #   types: [published]

jobs:
  build_push:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: install_dependencies
        run: |
          pip install GitPython
          pip install yaenv
        shell: bash

      - name: bump_version
        run: |
          git tag | tail -1
        shell: bash

      # - name: build
      #   run: |
      #     TODO
      
      # - name: upload
      #   run: 
      #     TODO
