name: Build Package and Push

on:
  push:
    branches:
      - master
  # release:
  #   types: [published]

jobs:
  build_push:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: install_dependencies
        run: |
          pwd
          ls -a
          which python
          python --version
          which pip
          pip --version
        shell: bash
      
      # - name: build
      #   run: |
      #     TODO
      
      # - name: upload
      #   run: 
      #     TODO
