name: Build Package and Push

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build_push:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: install_dependencies
        run: |
          pip install GitPython
          pip install yaenv
        shell: bash

      - name: bump_version
        run: |
          echo "[INFO] Get latest tag"
          git fetch --all --tags
          RELEASE_VERSION=$(git tag | tail -1)
          RELEASE_VERSION=$(echo $RELEASE_VERSION | sed s/v//)
          echo $RELEASE_VERSION

          echo "[INFO] Get current version"
          CURRENT_VERSION=$(cat src/init.py | grep "__version__" | grep -oP "([0-9]*\.[0-9]*\.[0-9]*)")
          echo $CURRENT_VERSION

          echo "[INFO] Bump version"
          sed -i s/$CURRENT_VERSION/$RELEASE_VERSION/ src/init.py

          echo "[INFO] Commit and push"
          git add src/init.py
          git commit -m "Bump version from $CURRENT_VERSION to $RELEASE_VERSION"

      - name: clean
        run: |
          rm -rf ./build/ && rm -rf ./dist/

      - name: build
        run: |
          python setup.py sdist bdist_wheel

      - name: check
        run:
          python -m twine check dist/*

      - name: upload
        run: |
          python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

      - name: commit_push
        run: |
          git push
